server.port=8080
spring.application.name=gateway-service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway Routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route CLIENT-SERVICE
spring.cloud.gateway.routes[0].id=client-service
spring.cloud.gateway.routes[0].uri=lb://client-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clients/**

# Route COMPTE-SERVICE
spring.cloud.gateway.routes[1].id=compte-service
spring.cloud.gateway.routes[1].uri=lb://compte-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/comptes/**

# Route OPERATION-SERVICE
spring.cloud.gateway.routes[2].id=operation-service
spring.cloud.gateway.routes[2].uri=lb://operation-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/operations/**

# Circuit Breaker
resilience4j.circuitbreaker.instances.default.sliding-window-size=10
resilience4j.circuitbreaker.instances.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=10000

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
